### ISSUE TITLE
Honor # noqa comments to suppress warnings

### ISSUE THREAD

**Issue by johnthagen** [zheller/flake8-quotes#10]
Flake8 states ``lines that contain a # noqa comment at the end will not issue warnings``.
Reference: https://pypi.python.org/pypi/flake8

I would suggest adding the following test:
```python
s = "Hello"  # noqa
```

The ``pep8`` package has a ``noqa()`` function you can use like:
```python
    import pep8
    if pep8.noqa(physical_line):
        ...
```

**Comment by twolfson** [comment]
There are already tests against `noqa`:

https://github.com/zheller/flake8-quotes/blob/d2e56964efc86a97d63e5a75f1af157da1608290/test/data/doubles_noqa.py

https://github.com/zheller/flake8-quotes/blob/d2e56964efc86a97d63e5a75f1af157da1608290/test/test_checks.py#L32-L34

What's a test case where that's failing?

**Comment by johnthagen** [comment]
I'm pretty sure when I submitted this I was using a version published on PyPI that was out of date with the latest fixes on github. Since then, a new version has been published to PyPI with the fixes, so this issue can be closed.

**Comment by twolfson** [comment]
Ah, cool. Thanks =)
