### ISSUE TITLE
Friendlier error message

### ISSUE THREAD

**Issue by Julian** [zheller/flake8-quotes#102]
Hi. I was looking to add a linter for string literals to a project of mine and found this one, thanks for writing it.

I find the error message likely a bit too unclear for people however.

Specifically it'll tell someone to "remove bad quotes", when instead it seems clearer to say something of the form "Single quote string literal found, this codebase uses double quoted literals" (or vice versa based on the config).

Are you open to changing it?

**Comment by twolfson** [comment]
Not strongly opposed to it, though I could see it breaking some setups which expect consistent human readable output

Do you mind surveying other parts of `flake8` or plugins to see how they handle different user configurations? (e.g. line length messages, tabs vs spaces, casing)

**Comment by Julian** [comment]
Great! Sure thing.

Here's e.g. [pycodestyle](https://github.com/PyCQA/pycodestyle/blob/aa3417b6a51f5912e32d9c8c879e1b9dd660d5f8/pycodestyle.py#L319-L320) which for line length too long will say "(137 > whatyouconfiguredasmaxlinelength" (on the same E501 rule)

And a plugin for checking tabs and spaces [which does the same seemingly](https://gitlab.com/ntninja/flake8-tabs/-/blob/e730ad4b2c82fa2e2af8b5478902efc137abb90d/flake8_tabs/indentationck.py#L79-88), using a single rule but modifying the text for human readability depending on if tabs or spaces are configured.

**Comment by twolfson** [comment]
Awesome, thanks @Julian =D

I'm now much more comfortable with changing the text =) We're prob fine to leave them using the same code. If people eventually request it, then we can make that a breaking change (major release) then.

Do you mind opening a PR to introduce the change? Best approach will prob be putting the full message into the `INLINE_QUOTES`/`MULTILINE_QUOTES` config -- this will futureproof us for i18n if that ever comes up (e.g. syntax/ordering in 1 language can be unpredictable)

https://github.com/zheller/flake8-quotes/blob/461254935334d3877c7c0990a39fe6c74494a207/flake8_quotes/__init__.py#L25-L53

**Comment by Julian** [comment]
Sure thing. Sent.

**Comment by twolfson** [comment]
This has been released in `flake8-quotes@3.3.0`
