### ISSUE TITLE
Test in Travis CI

### ISSUE THREAD

**Issue by twolfson** [zheller/flake8-quotes#15]
It looks like we introduced a `.travis.yml` in #6 but it isn't currently being used. We should get this set up so we can automatically test Python 2 and Python 3. Otherwise, we should remove the unnecessary `.travis.yml`.

@zheller Thoughts?

**Comment by twolfson** [comment]
Bump on this issue. Waiting to hear back from @zheller =/

**Comment by zheller** [comment]
Sure, go ahead.

**Comment by twolfson** [comment]
Can you flip the switch in https://travis-ci.org/profile/zheller ? I can't since this is a personal repo =/

**Comment by zheller** [comment]
Ok, switch on travisci.org is switched.

**Comment by twolfson** [comment]
Awesome, thanks @zheller =D

**Comment by twolfson** [comment]
This has been resolved in #17 and was released in `0.2.1`.
