### ISSUE TITLE
Package version 0.2.3 egg is broken

### ISSUE THREAD

**Issue by do3cc** [zheller/flake8-quotes#23]
The egg does not contain the `VERSION` file.
the module tries to load the `VERSION` file during import time and fails.
I guess with this
https://github.com/zheller/flake8-quotes/blob/master/setup.py#L31

this line gets ignored:
https://github.com/zheller/flake8-quotes/blob/master/setup.py#L33

**Comment by Ichimonji10** [comment]
See #21.

**Comment by do3cc** [comment]
Pkg_resources really is the way to.

Release management really becomes a no brainer when following a few best practices documented and built upon in zest.releaser.

Von meinem iPhone gesendet

Am 16.02.2016 um 19:30 schrieb Ichimonji10 <notifications@github.com<mailto:notifications@github.com>>:


See #21<https://github.com/zheller/flake8-quotes/pull/21>.

-
Reply to this email directly or view it on GitHub<https://github.com/zheller/flake8-quotes/issues/23#issuecomment-184815564>.

________________________________________________________ The contents of this e-mail and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this e-mail is received in error, please immediately notify the sender and delete the e-mail and attached documents. Please note that neither the sender nor the sender's company accept any responsibility for viruses and it is your responsibility to scan or otherwise check this e-mail and any attachments.

**Comment by twolfson** [comment]
Sorry, I was under the impression @Ichimonji10 was taking care of this in #21 =/

**Comment by Ichimonji10** [comment]
Feel free to re-open and merge #21.

**Comment by twolfson** [comment]
Alright, it looks like #21 is off of the table. I will take a look at resolving this issue by the end of the weekend. In the meantime, please pin to a lower version:

```bash
pip install flake8-quotes<0.2.0,>=0.1.2
```

**Comment by twolfson** [comment]
PR #24 is now open to resolve this issue

**Comment by richrd** [comment]
Great to see this getting fixed! It's breaking my travis build :relaxed: :+1:

**Comment by twolfson** [comment]
Decided to cowboy land #24 due to the lack of review from @zheller. It's been landed/released in `0.2.4`
