### ISSUE TITLE
Add support for docstrings

### ISSUE THREAD

**Issue by jackwilsdon** [zheller/flake8-quotes#25]
I'd like to be able to enforce docstring quotes and normal string quotes separately, so I can require double quotes for docstrings and single quotes everywhere else.

Example of code that would pass the check (assuming we enforce double quotes for docstrings and single quotes for everything else):

``` python
def hello():
    """
    Prints "Hello, world!"
    """
    print('Hello, world!')
```

And an example of some code that would not pass using the aforementioned rules:

``` python
def hello():
    '''
    Prints "Hello, world!"
    '''
    print('Hello, world!')
```

``` python
def hello():
    '''
    Prints "Hello, world!"
    '''
    print("Hello, world!")
```

``` python
def hello():
    """
    Prints "Hello, world!"
    """
    print("Hello, world!")
```

**Comment by twolfson** [comment]
That seems reasonable to me. Would you be interested in opening a PR?

**Comment by jackwilsdon** [comment]
Hmm, so I've noticed something odd with how `flake8-quotes` works.

For some reason, this code passes fine?

```python
def hello():
    """
    Prints "Hello, world!"
    """
    print('Hello, world!')
```

I am using the default value for `quotes`, which is single.

**Comment by twolfson** [comment]
Yea, this repo is looser than one would assume. In my experience `esformatter-quotes` had the ideal configuration:

https://github.com/millermedeiros/esformatter-quotes

**Comment by thecardcheat** [comment]
@twolfson  It looks like this sort of functionality is supplied by [pydocstyle](http://www.pydocstyle.org/en/latest/) which has a [flake8 adapter](https://pypi.python.org/pypi/flake8-docstrings) so you might not want to bother adding it here.

**Comment by twolfson** [comment]
Ah, neat. Thanks for the heads up @thecardcheat. I think we'll still want multiline string support -- maybe not exclusively in the context of docstrings (e.g. a large chunk of inlined text). It's not clear if `pydocstyle` supports that =/

**Comment by twolfson** [comment]
This has been added in `0.10.0` via @batlock666 in #52
