### ISSUE TITLE
Reasoning behind limiting flake8 to version below 2.6 in tests

### ISSUE THREAD

**Issue by xZise** [zheller/flake8-quotes#36]
Is there a reason why `requirement-dev.txt` requires `flake8<2.6.0,>=2.5.0`? Shouldn't any version above 2.5 and below 3.0 work (or with #34 also above 3.0)?

**Comment by twolfson** [comment]
It's for less volatility in versioning which leads to less developer frustration/maintenance. While SemVer says to keep all minor releases backwards compatible, it isn't always the case.
