### ISSUE TITLE
Disable help text for --quotes parameters?

### ISSUE THREAD

**Issue by xZise** [zheller/flake8-quotes#40]
It is possible in `optparse` to [suppress the help text](https://docs.python.org/3.5/library/optparse.html#optparse.Option.help). As the `--quotes` argument is deprecated, this could be suppressed? Or should it still be visible to give users the ability to see what it does when someone else is using it?

**Comment by twolfson** [comment]
`--quotes` won't be deprecated to until a multiline PR is landed. At that point, we want to keep the option visible so people can see that it's deprecated until we remove it.
