### ISSUE TITLE
flake8 3.5+ support

### ISSUE THREAD

**Issue by themusicgod1** [zheller/flake8-quotes#64]
Right now the default flake8 that will be used in the next version of Ubuntu GNU/Linux (Ubuntu 18.04) will be 3.5.  Similarly, the flake8 in the "buster" / testing flavour of Debian GNU/Linux is at 3.5 - that will be the next version of Debian, to be released at some point.

And yet the requirements-dev lists the required flake8 is '<3.4.0,>=3.3.0'

Especially given an expressed interest in incorporating flake8-quotes into Debian/Ubuntu ( Debian RFP# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887115 ), it will be worthwhile to expand to support the version of flake8 actually present in the next version of Debian/Ubuntu.

If there's nothing to add to add this support...it might be a matter of just changing requirements-dev.txt

**Comment by themusicgod1** [comment]
See #66

**Comment by twolfson** [comment]
Flake8's version is is exclusively being specified for development. During development of any Python package, it's encouraged to use virtualenv/similar to isolate dependencies from global dependencies

Closing this as `wontfix`
