### ISSUE TITLE
tox 2.5+ support

### ISSUE THREAD

**Issue by themusicgod1** [zheller/flake8-quotes#65]
Same as #64 only for tox.  requirements-dev.txt lists tox versions tox<2.4.0,>=2.3.1 - but the current version of tox in even Debian Stable is 2.5

**Comment by themusicgod1** [comment]
See #66

**Comment by twolfson** [comment]
Tox is exclusively being used for development. During development of any Python package, it's encouraged to use `virtualenv`/similar to isolate dependencies from global dependencies

Closing this as `wontfix`

**Comment by themusicgod1** [comment]
virtualenv will only work if tox versions in question are actually available, which they are not assumed to be in the case of Debian, including but not limited to for purposes of development

**Comment by twolfson** [comment]
`virtualenv` supports ignoring system level packages via the `--no-site-packages` flag. Have you tried that out?

**Comment by themusicgod1** [comment]
I only use system level packages.  The goal here is to expand the scope of audited, supported, reproducible system-level packages.  PyPy will not necessarily be around forever and cannot be counted on to be secure.  However if you are choosing not to support outside-of PyPy use that is totally fine - it's your project and I respect that.  I will do what I can outside of this repo to make sure flake8-quotes gets in without your assistance or the dependency upon it is removed.  Thank you for your time.

**Comment by twolfson** [comment]
Ah, I understand. Thanks for understanding our perspective and good luck!
