### ISSUE TITLE
Tag new release for PyPI

### ISSUE THREAD

**Issue by rouge8** [zheller/flake8-quotes#7]
Now that #6 is merged, can you tag a new release for PyPI?

**Comment by adrianmoisey** [comment]
That would be rad!

**Comment by 2m** [comment]
+1

**Comment by 2m** [comment]
In the mean time, as a reminder, note that setuptools can install packages from github URLs as well. [Here is an example](https://github.com/2m/conductr-cli/blob/caa56090d349c3f150cca4aa0fa6db0c7da70582/tox.ini#L12) of how this linter can be used in a tox setup.

**Comment by hvelarde** [comment]
any news on that release?

**Comment by johnthagen** [comment]
What is the plan to push a new release?  Need the update on PyPI for easy installation.  The PyPI package doesn't have #1 issue fixed.

**Comment by theandrewdavis** [comment]
Agreed, I'm also waiting on a PyPI update.

**Comment by twolfson** [comment]
Hey folks, sorry for the delay on this. We have released `0.1.0` to PyPI:

https://pypi.python.org/pypi/flake8-quotes/0.1.0

**Comment by hvelarde** [comment]
I think you meant 0.1.1: https://pypi.python.org/pypi/flake8-quotes/0.1.1

**Comment by twolfson** [comment]
Nope, I meant `0.1.0`. There was a patch release shortly after from #11 which lead to `0.1.1` =)
