### ISSUE TITLE
Allow both single and double for inline but enforce double for docstring

### ISSUE THREAD

**Issue by stevula** [zheller/flake8-quotes#76]
I would like to require double quotes for docstrings but allow people to use single or double quotes for inline strings as they prefer. Is this possible?

**Comment by meshy** [comment]
Sounds like a job for https://github.com/PyCQA/flake8-docstrings

**Comment by twolfson** [comment]
I'm with @meshy on this. There seems to be a library that already supports this. That being said, I'm happy to accept a PR which adds said support

Closing issue as `wontfix` for now

**Comment by stevula** [comment]
Fair enough! Thanks for the recommendation.
