### ISSUE TITLE
Duplicate work

### ISSUE THREAD

**Issue by txomon** [zheller/flake8-quotes#8]
Hi, I have been coding past week also a flake8-quotes project, and when I tried to register my project, found this one here.

I will be changing the name of my project, but just in case you are interested, have a link https://github.com/txomon/flake8-quotes

I use combination of ast and file reading to parse correctly all the strings. Although for the moment I haven't finished the work (I don't support multi quote strings nor docstrings yet).

Have a nice day!

**Comment by johnthagen** [comment]
I too wrote a module for string quote checking before stumbling across this on PyPI.  I haven't uploaded mine to PyPI (probably won't now that there are already packages), but thought I should share my code on this issue as well: https://github.com/johnthagen/flake8-strings

**Comment by txomon** [comment]
@johnthagen I pretty much like yours... making configurable what it should look like. In my case is because I always force single quotes.

Also mine doesn't support docstrings yet. I don't see them as important, but will be supported in the future. Does yours have any feature you would like to highlight?

**Comment by twolfson** [comment]
Going to close this issue since there isn't anything explicit about this repo's features and this repo seems to be created before both of them =/
