### ISSUE TITLE
Q003 error message is wrong for raw strings

### ISSUE THREAD

**Issue by xqt** [zheller/flake8-quotes#80]
I guess _Q003: Change outer quotes to avoid escaping inner quotes_ was introduced with flake8-quotes 2.0.0 but this error is not appropriate for raw strings; e.g. `r'\'' == r"\'"` but the escape sequence cannot be omitted. Therefore there is no need to change the outer bound quotes in such cases.

**Comment by twolfson** [comment]
@zheller Can you set me as an admin on this repo? I'd like to add @JoeHitchen as a contributor so they can handle this independently

**Comment by zheller** [comment]
yah

**Comment by zheller** [comment]
Couldnt figure out how to add you as an admin so just added @JoeHitchen as a collab

**Comment by twolfson** [comment]
Great, thanks!

@JoeHitchen Are you free to handle this issue? If so, do the normal PR submission. If neither @zheller or myself are available to review (wait 24 hours), then you're prob fine to land it yourself

Also, please give us your PyPI handle so you can release there (we release via `./release.sh <semver>`)

**Comment by JoeHitchen** [comment]
Yeah, I'll look into this. I'm not set up on PyPI, but I can create an account if needed.

**Comment by twolfson** [comment]
Can you create an account so we can add you? #81 looks good and I should land it later tonight but I want to set everything up for "just in case"

**Comment by twolfson** [comment]
This has been resolved by @JoeHitchen in #81 and released in `2.0.1`

**Comment by JoeHitchen** [comment]
Eventually, I have set myself up as JoeHitchen in PyPI

**Comment by twolfson** [comment]
Back from vacation and glad to see nothing bad happened =D Adding you to PyPI 👍
