### ISSUE TITLE
Document all the validation codes in the README

### ISSUE THREAD

**Issue by peterjc** [zheller/flake8-quotes#83]
The README currently says:

> This package adds one flake8 warning `Q0`. 

This is misleading, it looks like it currently defines four warnings which can all be enabled or disabled with the partial code `Q0`:

* Q000 Remove bad quotes
* Q001 Remove bad quotes from multiline string
* Q002 Remove bad quotes from docstring
* Q003 Change outer quotes to avoid escaping inner quotes

**Comment by twolfson** [comment]
Ah, good catch. Do you think updating the text to "This package adds flake8 warnings with the prefix `Q0`" would work for you?

I think we explain each problem in the `flake8` output (e.g. `Q000 Remove bad quotes`)

**Comment by peterjc** [comment]
Personally I find it really useful for the plugin documentation to list _all_ the codes, this is especially useful when reviewing flake8 settings for a large project. So I list them all in a table, e.g.

https://github.com/peterjc/flake8-black#flake8-validation-codes
https://github.com/peterjc/flake8-rst-docstrings#flake8-validation-codes

In any case, your proposed wording is a good improvement.

**Comment by twolfson** [comment]
Cool, I'm super busy this week but I'll try to get that update in by the end of the weekend
