### ISSUE TITLE
Ignrones print statements

### ISSUE THREAD

**Issue by BarakBD-Globality** [zheller/flake8-quotes#87]
setup.cfg
```
[flake8]
inline-quotes = double
```

My ocde:
```
print('success - s3.upload_file')
```
Run
```
flake8
```

Expected - Error.
Result - no error show

**Comment by twolfson** [comment]
Can you verify that `flake8-quotes` is indeed being loaded by `flake8`? Maybe put in 2 different lines with different sets of quotes to guarantee at least 1 error:

```
print('success - s3.upload_file')
print("success - s3.upload_file")
```

**Comment by BarakBD-Globality** [comment]
My bad, I had a general `noqa` instead of `noqa: T001` (ignore only print). Closing issue.
