### ISSUE TITLE
Add test cases for python3.7 and python3.8

### ISSUE THREAD

**Issue by sobolevn** [zheller/flake8-quotes#89]
Currently both `tox.ini` and `travis.yml` do not support latest python versions.

I can send a PR with the fix! 

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by twolfson** [comment]
Are you saying that the latest Python versions are broken or that we simply
aren't testing them?

**Comment by sobolevn** [comment]
I don't think that they are broken 🙂 

But, tests should tell us that!

**Comment by sobolevn** [comment]
Yeap, they are failing 🥇
