### ISSUE TITLE
Use flake8 provided tokens for analysis

### ISSUE THREAD

**Issue by skirpichev** [zheller/flake8-quotes#93]
The current flake8-quotes implementation don't use the infrastructure, provided by flake8 for plugins.  The entry point `QuoteChecker` supports `tree` and `filename` arguments, but the first one (which is for AST tree, provided by flake8) - totally ignored!  Then, QuoteChecker parses provided file by itself, which will lead to "invalid" issues like https://github.com/zheller/flake8-quotes/issues/92.

I believe, this is a wrong situation and you could use instead the following skeleton to run checks per physical lines, provided by flake8:
```
$ cat flake8_demo/setup.py 
from setuptools import find_packages, setup

setup(
  name='flake8-demo',
  packages=find_packages(),
  entry_points={
    'flake8.extension': [
      'X801 = flake8_demo.checker:demo_checker'],
  },
)
$ cat flake8_demo/flake8_demo/__init__.py 
$ cat flake8_demo/flake8_demo/checker.py 
import pprint


def demo_checker(physical_line, tokens):
    pprint.pprint(physical_line)


demo_checker.name = 'demo_checker'
demo_checker.version = '0.0.1'
```

This plugin correctly get input, provided by flake8/flake8-rst.  For example:
```
$ cat demo.rst
Demo for flake8-rst and quotes

>>> a = "spam"
>>> f"no so short "
... f" formatted string with {a}"
'not so short formatted string with spam'

$ flake8-rst demo.rst 
'a = "spam"\n'
'f"no so short "\n'
'f" formatted string with {a}"\n'
demo.rst:3:5: D100 Missing docstring in public module
demo.rst:5:5: I002 no configuration found (.isort.cfg or [isort] in configs)
"""

**Comment by twolfson** [comment]
It's been a white since we've worked on the core of this package. It was initially developed under Flake8@2.x with lacking documentation and flexibility so we had to use `tokenize` to get the behavior we wanted

If you believe this behavior now exists in Flake8@3.x and is backwards compatible to Flake8@2.x, then feel free to open a PR to fix it

If I recall correctly, we ignored the AST parameter as it didn't contain the quote which is the whole point of this package and taking single lines as input doesn't work for multiline quotes

Closing this issue as `question` since it seems like it's asking "Are you sure you implemented this package correctly"?

If you believe it's still the case and correctly update our implementation/tests, please open a PR with a fix

**Comment by twolfson** [comment]
Upon further reading of your latest notes in #92, you might be onto something but I'm unconvinced that `flake8` actually supports what you claim -- a full set of the source code via an input parameter which we can join and `tokenize` (to support multiline strings iirc)

I don't have time to explore this

Feel free to explore/submit a PR for it but I feel what `flake8-rst` is doing is likely pushing the limits of `flake8` design intentions

**Comment by skirpichev** [comment]
> It's been a white since we've worked on the core of this package.

@twolfson, is it unmaintained now?   Why you are closing valid issues?!

> Closing this issue as question since it seems like it's asking "Are you sure you implemented this package correctly"?

No, I'm not asking this.  Now I'm pretty sure - this package was implemented incorrectly.   You may lack time to fix this, that's understandable.

> If you believe this behavior now exists in Flake8@3.x and is backwards compatible to Flake8@2.x,

I didn't check flake8 2.x, but IIRC - the mentioned above example should work as-is too.  Anyway, is the compatibility with 2.x - an important thing?  Both flake8 and flake8-quotes seems to be a developer-only things, which, as I believe, may use more strict version requirements than usual package dependencies...  BTW, even the Debian stable has flake8==3.6.

> If you believe it's still the case and correctly update our implementation/tests, please open a PR with a fix

What if someone else will provide such a PR?  By closing a valid issue you give users an impression, that there is no problem with your plugin.

> I feel what flake8-rst is doing is likely pushing the limits of flake8 design intentions

I doubt it's true.  Other plugins, which don't use such hacks like flake8-quotes - works fine (both ast-checkers like flake8-comprehensions and flake8-todo, which is implemented like the above example).

**Comment by twolfson** [comment]
> @twolfson, is it unmaintained now? Why you are closing valid issues?!
This package is maintained on a per-issue basis. I've explained the rationale at the time of closing each issue. I prefer to pre-emptively close issues in case of unresponsive collaborators

From my perspective, there's still no proof that the example code you provided would support all our use cases

> I didn't check flake8 2.x, but IIRC - the mentioned above example should work as-is too. Anyway, is the compatibility with 2.x - an important thing? Both flake8 and flake8-quotes seems to be a developer-only things, which, as I believe, may use more strict version requirements than usual package dependencies... BTW, even the Debian stable has flake8==3.6.

I'm not 100% certain to be honest. While reviewing the `flake8` docs briefly I saw a mention of `2.x` and `3.x`, I'd probably look at the release dates for `2.x` to determine if it's worth supporting or not. If `3.x` has been out for over a year, then probably not

> What if someone else will provide such a PR? By closing a valid issue you give users an impression, that there is no problem with your plugin.

Without proof, then from my perspective, there is nothing wrong in our repo but an issue in either `flake8` (for lacking infrastructure to support what `flake8-rst` is trying to do) or `flake8-rst` (for being outside of what `flake8` considers acceptable)

This reminded me that I talked to `flake8` about this previously, so there probably has been progress on it: https://gitlab.com/pycqa/flake8/issues/102

> I doubt it's true. Other plugins, which don't use such hacks like flake8-quotes - works fine (both ast-checkers like flake8-comprehensions and flake8-todo, which is implemented like the above example).

Both of these examples are single line usages and can rely on AST. The nature of quotes needs to go beyond the AST since the interpretter doesn't care what quote was used, only the contents inside it once parsed

**Comment by skirpichev** [comment]
>  I prefer to pre-emptively close issues in case of unresponsive collaborators

(I doubt you will have collaborators with such a policy...)

> there's still no proof that the example code you provided would support all our use cases

For me, common sense suggest that it's you should provide an explanation why the flake8 infrastructure doesn't fit your plugin.

So far, you only have referenced some issue in the flake8 repo.  Which is fixed.

> so there probably has been progress on it: https://gitlab.com/pycqa/flake8/issues/102

Yes, it's fixed.

> Without proof, then from my perspective

Which proof will convince you?  Can you provide a minimal example you do care about?

> Both of these examples are single line usages and can rely on AST.

Not all.  flake8-todo doesn't use AST.

**Comment by twolfson** [comment]
By collaborators, I mean anyone who opens an issue on a repo and there's plenty of unresponsive persons there

Yes, let me review our test cases briefly for minimal examples...

Here's a couple:

- Multiline strings, https://github.com/zheller/flake8-quotes/blob/2.1.1/test/data/docstring_doubles.py
    - Test run via: https://github.com/zheller/flake8-quotes/blob/2.1.1/test/test_docstring_checks.py#L8-L25
- Stdin support: https://github.com/zheller/flake8-quotes/blob/2.1.1/test/test_checks.py#L13-L27

For your own sanity, it might be easier to clone our repo and run our tests directly

If you can prove that `flake8` now supports these use cases with our `tokenizer` implementation (or if `flake8` provides appropriate tokens now), then I'll reopen this issue and mark it as `help wanted`

**Comment by skirpichev** [comment]
> Yes, let me review our test cases briefly for minimal examples...

By a minimal example I didn't mean all your test suite.

> I'll reopen this issue and mark it as help wanted

I think, it will be easier to write plugin I need from scratch.  Your issue "fixing" approach scare me.

@twolfson, lets me try the last attempt to convince you.  Here is an example of two sources, both include multiline strings.  As you can see, my plugin ("X" prefixes) correctly handles both *.py and *.rst (the slight difference for *.py output is that I point to the first quote symbol, while your plugin points to the prefix), while flake8-quotes produce a garbage for demo.rst:
```
$ cat demo.rst 
Demo for flake8-rst and quotes

>>> a = "spam"
>>> f"no so short "
... f" formatted string with {a}"
'not so short formatted string with spam'
>>> """ this
... is an example of "multiline"
... string
... """
' this\nis an example of "multiline"\nstring\n'
>>> '''
... is an example of "multiline"
... string
... '''
'\nis an example of "multiline"\nstring\n'

$ flake8-rst --ignore="D,I" demo.rst --show-source
demo.rst:3:9: X800 Remove bad quotes
>>> a = "spam"
        ^
demo.rst:4:6: X800 Remove bad quotes
>>> f"no so short "
     ^
demo.rst:5:6: X800 Remove bad quotes
... f" formatted string with {a}"
     ^
demo.rst:5:13: Q000 Remove bad quotes
... f" formatted string with {a}"
            ^
demo.rst:7:9: Q000 Remove bad quotes
>>> """ this
        ^
demo.rst:8:9: Q000 Remove bad quotes
... is an example of "multiline"
        ^
demo.rst:12:5: X801 Remove bad quotes from multiline string
>>> '''
    ^

$ cat demo.py 
a = "spam"
f"no so short "
f" formatted string with {a}"
""" this
is an example of "multiline"
string
"""
'''
is an example of "multiline"
string
'''

$ flake8 --ignore="D,I" demo.py --show-source
demo.py:1:5: X800 Remove bad quotes
a = "spam"
    ^
demo.py:1:5: Q000 Remove bad quotes
a = "spam"
    ^
demo.py:2:1: Q000 Remove bad quotes
f"no so short "
^
demo.py:2:2: X800 Remove bad quotes
f"no so short "
 ^
demo.py:3:1: Q000 Remove bad quotes
f" formatted string with {a}"
^
demo.py:3:2: X800 Remove bad quotes
f" formatted string with {a}"
 ^
demo.py:8:1: X801 Remove bad quotes from multiline string
'''
is an example of "multiline"
string
'''
^
demo.py:8:1: Q001 Remove bad quotes from multiline string
'''
^
```

**Comment by twolfson** [comment]
Okay, after staring at this for a few minutes I think I see the relevant parts of the code block. You're saying that the `flake8-demo` code from the first comment (https://github.com/zheller/flake8-quotes/issues/93#issue-587617013) is generating these X801 lines

```
demo.py:8:1: X801 Remove bad quotes from multiline string
'''
is an example of "multiline"
string
'''
^
```

and that is proof that `flake8` has a plugin API for passing individual lines without parsing

I'm a little confused and skeptical still. For example, this line clearly is only a partial line:

```
demo.rst:12:5: X801 Remove bad quotes from multiline string
>>> '''
```

For our plugin to properly lint, we need all surrounding lines to verify the ending quotes match

Am I missing something here?

**Comment by skirpichev** [comment]
> You're saying that the flake8-demo

A little enhanced version, yes.

> For our plugin to properly lint, we need all surrounding lines to verify the ending quotes match

I think, this is that it.  Here is the source (docstring special case isn't implemented):
```python
import tokenize


seen = []


def str_checker(physical_line, tokens):
    for token in tokens:
        if token.type != tokenize.STRING:
            continue

        last_quote_char = token.string[-1]
        first_quote_index = token.string.index(last_quote_char)
        prefix = token.string[:first_quote_index].lower()
        unprefixed_string = token.string[first_quote_index:]

        is_multiline_string = unprefixed_string[0] * 3 == unprefixed_string[0:3]
        start_row, start_col = token.start

        if unprefixed_string != token.string:
            start_col += len(prefix)

        if is_multiline_string:
            if token in seen:
                continue
            else:
                seen.append(token)

            if '"""' in  unprefixed_string:
                continue
            yield start_col, 'X801 Remove bad quotes from multiline string'

        else:
            string_contents = unprefixed_string[1:-1]

            if last_quote_char == "'":
                if 'r' in prefix:
                    continue
                if "'" in string_contents and not '"' in string_contents:
                    yield start_col, 'X803 Change outer quotes to avoid escaping inner quotes'
                continue
            if not "'" in string_contents:
                yield start_col, 'X800 Remove bad quotes'


str_checker.name = 'str_checker'
str_checker.version = '0.0.1'
```

**Comment by twolfson** [comment]
I see, thanks for providing that =) I'm still a little skeptical that we'll get `tokenize` working appropriately across multiple lines but I guess that's for the PR to figure out

Re-opening issue with "help wanted" as promised and updating title from "Incorrect plugin implementation" to "Use flake8 provided tokens for analysis"
